apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo_1-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo_1

  template:
    metadata:
      labels:
        app: demo_1

    spec:
      containers:
        - name: demo_1

          image: pramod1906/demo_1:latest

          ports:
            - containerPort: 8080